CREATE TABLE artigos (
    id NUMBER(19) PRIMARY KEY,
    titulo VARCHAR2(255) NOT NULL,
    conteudo CLOB NOT NULL,
    autor VARCHAR2(100) NOT NULL,
    data_publicacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE artigos_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER artigos_bir
BEFORE INSERT ON artigos
FOR EACH ROW
BEGIN
    IF :NEW.id IS NULL THEN
        SELECT artigos_seq.NEXTVAL INTO :NEW.id FROM dual;
    END IF;
END;
